name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        uses: sudo docker build -t flask-line-bot .

      - name: Run Docker Image
        uses: sudo docker run -p 5000:5000 flask-line-bot
