name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t flask-line-bot .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker tag flask-line-bot:latest <your-dockerhub-username>/flask-line-bot:latest
        run: docker push <your-dockerhub-username>/flask-line-bot:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull <your-dockerhub-username>/flask-line-bot:latest
            docker stop flask-line-bot || true
            docker run -d -p 5000:5000 --name flask-line-bot <your-dockerhub-username>/flask-line-bot:latest
