name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Deploy to Ubuntu Server
      run: |
        ssh -i "key.pem" ubuntu@ec2-3-104-64-155.ap-southeast-2.compute.amazonaws.com << EOF
          echo "Connected to the Ubuntu server";
          # Add deployment commands here, e.g.,
          cd /projects/afdc_shop_line_bot
          git pull origin main  
          sudo sudo docker build -t flask-line-bot .
          sudo sudo docker run -p 5000:5000 flask-line-bot
        EOF

      # - name: Deploy to Ubuntu Server
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}         
      #     username: ${{ secrets.SERVER_USER }}     
      #     key: ${{ secrets.SERVER_SSH_KEY }}       
      #     port: 22 
      #     script: |
      #       cd /projects/afdc_shop_line_bot
      #       git pull origin main  
      #       sudo sudo docker build -t flask-line-bot .
      #       sudo sudo docker run -p 5000:5000 flask-line-bot

      
