name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 Instance
        run: |
          # Disable strict host key checking to avoid host key verification failure
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ec2-3-104-64-155.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        
          # SSH into EC2 instance
          ssh -i key.pem ubuntu@ec2-3-104-64-155.ap-southeast-2.compute.amazonaws.com << EOF
            echo "Connected to the EC2 instance!";
            cd projects/afdc_shop_line_bot
            git pull origin main
            sudo docker build -t flask-line-bot . 
            sudo docker stop flask-line-bot
            sudo docker rm flask-line-bot
            sudo docker run -d --name flask-line-bot -p 5000:5000 flask-line-bot
          EOF


      
